module.exports = {
  content: ['_site/**/*.html'],
  css: ['css/**/*.css'],
  output: 'cleancss',
  safelist: [
    'all_passing',
    'bi',
    'bol',
    'close',
    'curly',
    'cursor',
    'description',
    'eol',
    'error',
    'expected',
    'fail',
    'functionCall',
    'github-user',
    'got',
    'highlight',
    'log',
    'marker',
    'message',
    'no_results',
    'no_results',
    'open',
    'output',
    'paren',
    'pass',
    'pills',
    'prompt',
    'result',
    'results',
    'some_failing',
    'square',
    'summary',
    'text',
    'value',
    'wrong-bracket',
  ],
};
